server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchange/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

      discovery:
        locator:
          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

