server:
  port: 8083

spring:
  application:
    name: api-gateway

  r2dbc:
    url: r2dbc:postgresql://localhost:5430/habrdb
    username: habrpguser
    password: pgpwd4habr
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 738731464570-jpv9e4soboc6as3cl2rc6pq89qt2ict8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:3000/oauth2/redirect/{registrationId}" #"http://localhost:8080/login/oauth2/code/{registrationId}"
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: exchange-service
#          uri: lb://exchange-service
#          predicates:
#            - Path=/exchange/**
#          filters:
#            - Authentication
#
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsKUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF4O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
