server:
  port: 8083

spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: exchange-service
#          uri: lb://exchange-service
#          predicates:
#            - Path=/exchange/**
#          filters:
#            - Authentication
#
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka